replicaCount: 1

image:
  repository: lanchonetews
  tag: latest
  pullPolicy: Always

service:
  type: NodePort
  port: 3000

lanchonetews:
  service:
    port: 3000
  env:
    host: "http://lanchonetews:3000/api/payment-status"
    port: "3001"

resources: {}
