replicaCount: 1

image:
  repository: lanchonetews
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

lanchonetews:
  service:
    port: 3000
  env:
    host: "http://lanchonetews:3000/api/payment-status"
    port: "3001"
  db:
    dbHost: ${{secrets.DB_HOST}}
    dbPort: ${{secrets.DB_PORT}}
    dbUser: ${{secrets.DB_USER}}
    dbPassword: ${{secrets.DB_PASSWORD}}
    database: ${{secrets.DATABASE}}

resources: {}
