apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonetews-config
data:
  config.yaml: |
    DB_DATABASE: {{ .Values.db.database}}
    DB_PORT: {{ .Values.db.port }}
    DB_USER: {{ .Values.db.user }}
    DB_PASSWORD: {{ .Values.db.password }}
    DB_HOST: {{ .Values.db.host }} 

    HOST: {{ .Values.host}} 
    PORT: {{.Values.port}}
