apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonetews-config
data:
  DB_HOST: postgresql
  DB_USER: dbadmin
  DB_PASSWORD: lanchonetews
  DB_DATABASE: lanchonetews
  DB_PORT: "5432"
  PORT: "3001"
  HOST: "http://lanchonetews:3000/api/payment-status"
