apiVersion: v1
kind: ConfigMap
metadata:
  name: lanchonetews-config
data:
  config.yaml: |
    DB_DATABASE: {{ .Values.db.database}}
    DB_PORT: {{ .Values.db.dbPort }}
    DB_USER: {{ .Values.db.dbUser }}
    DB_PASSWORD: {{ .Values.db.dbPassword }}
    DB_HOST: {{ .Values.db.dbHost }} 

    HOST: {{ .Values.host}} 
    PORT: {{.Values.port}}
