apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonetews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonetwsapp
  template:
    metadata:
      labels:
        app: lanchonetwsapp
    spec:
      containers:
        - name: lanchonetews
          image: wstecnologia/lanchonetews:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: DB_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: DB_DATABASE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: DB_PORT
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: DB_PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: lanchonetews-config
                  key: DB_HOST
          periodSeconds: 30
