apiVersion: v1
kind: Service
metadata:
  name: lanchonetews
  labels:
    app: lanchonetwsapp
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: lanchonetwsapp
