apiVersion: v1
kind: Service
metadata:
  name: techchallenge-webhook
  labels:
    app: lanchonetwsapp
spec:
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: lanchonetwsapp
