name: Deploy AWS Academy - EKS

on:
  push:
    branches:
      - develop
      - main

env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "EKS_WSTECH"
  RELEASE_NAME: "lanchonetews"
  NAMESPACE: "default"

jobs:
  deploy:
    name: Deploy AWS Academy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Install Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt-get update && sudo apt-get install -y terraform
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      #   working-directory: ./terraform
      # - name: Update kubeconfig for EKS
      #   run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION_DEFAULT }}

      - name: Helm Install or Upgrade
        run: |
          helm install lanchonetews k8s/
